# Dockerfile - Entraînement (training)
FROM python:3.10-slim

WORKDIR /app

# Copier les fichiers nécessaires
COPY . .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Créer le dossier des modèles
RUN mkdir -p /app/models